//! Kani proof harness for Solana account: Withdraw
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 7

/// Symbolic representation of the Solana account for verification
struct SymbolicWithdraw {
    vault: u64,
    user_shares: u64,
    user_token: u64,
    vault_token: u64,
    user: u64,
    token_program: u64,
}

impl kani::Arbitrary for SymbolicWithdraw {
    fn any() -> Self {
        Self {
            vault: kani::any(),
            user_shares: kani::any(),
            user_token: kani::any(),
            vault_token: kani::any(),
            user: kani::any(),
            token_program: kani::any(),
        }
    }
}

/// Verify: vault is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_0() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: vault is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'vault is writable  /* Account marked as mutable */' */ }, "Invariant violation: vault is writable  /* Account marked as mutable */");
}

/// Verify: vault PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_1() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: vault PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'vault PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: vault PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: user_shares is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_2() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user_shares is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'user_shares is writable  /* Account marked as mutable */' */ }, "Invariant violation: user_shares is writable  /* Account marked as mutable */");
}

/// Verify: user_shares PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_3() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user_shares PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'user_shares PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: user_shares PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: user_token is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_4() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user_token is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'user_token is writable  /* Account marked as mutable */' */ }, "Invariant violation: user_token is writable  /* Account marked as mutable */");
}

/// Verify: vault_token is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_5() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: vault_token is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'vault_token is writable  /* Account marked as mutable */' */ }, "Invariant violation: vault_token is writable  /* Account marked as mutable */");
}

/// Verify: user.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_6() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ user.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: user.is_signer == true  /* Anchor Signer type enforces signer check */");
}

