//! Kani proof harness for Solana account: ExtendLock
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 3

/// Symbolic representation of the Solana account for verification
struct SymbolicExtendLock {
    escrow: u64,
    owner: u64,
}

impl kani::Arbitrary for SymbolicExtendLock {
    fn any() -> Self {
        Self {
            escrow: kani::any(),
            owner: kani::any(),
        }
    }
}

/// Verify: escrow is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_extendlock_constraint_0() {
    let account: SymbolicExtendLock = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: escrow is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'escrow is writable  /* Account marked as mutable */' */ }, "Invariant violation: escrow is writable  /* Account marked as mutable */");
}

/// Verify: escrow PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_extendlock_constraint_1() {
    let account: SymbolicExtendLock = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: escrow PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'escrow PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: escrow PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: owner.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_extendlock_constraint_2() {
    let account: SymbolicExtendLock = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: owner.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ owner.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: owner.is_signer == true  /* Anchor Signer type enforces signer check */");
}

