//! Kani proof harness for Solana account: VoteOnProposal
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 5

/// Symbolic representation of the Solana account for verification
struct SymbolicVoteOnProposal {
    escrow: u64,
    proposal: u64,
    user: u64,
}

impl kani::Arbitrary for SymbolicVoteOnProposal {
    fn any() -> Self {
        Self {
            escrow: kani::any(),
            proposal: kani::any(),
            user: kani::any(),
        }
    }
}

/// Verify: escrow is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_voteonproposal_constraint_0() {
    let account: SymbolicVoteOnProposal = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: escrow is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'escrow is writable  /* Account marked as mutable */' */ }, "Invariant violation: escrow is writable  /* Account marked as mutable */");
}

/// Verify: escrow PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_voteonproposal_constraint_1() {
    let account: SymbolicVoteOnProposal = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: escrow PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'escrow PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: escrow PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: proposal is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_voteonproposal_constraint_2() {
    let account: SymbolicVoteOnProposal = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: proposal is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'proposal is writable  /* Account marked as mutable */' */ }, "Invariant violation: proposal is writable  /* Account marked as mutable */");
}

/// Verify: proposal PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_voteonproposal_constraint_3() {
    let account: SymbolicVoteOnProposal = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: proposal PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'proposal PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: proposal PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: user.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_voteonproposal_constraint_4() {
    let account: SymbolicVoteOnProposal = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ user.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: user.is_signer == true  /* Anchor Signer type enforces signer check */");
}

