//! Kani proof harness for Solana account: VerifyTransfer
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 3

/// Symbolic representation of the Solana account for verification
struct SymbolicVerifyTransfer {
    source: u64,
    destination: u64,
    mint: u64,
    authority: u64,
    token_program: u64,
}

impl kani::Arbitrary for SymbolicVerifyTransfer {
    fn any() -> Self {
        Self {
            source: kani::any(),
            destination: kani::any(),
            mint: kani::any(),
            authority: kani::any(),
            token_program: kani::any(),
        }
    }
}

/// Verify: source is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_verifytransfer_constraint_0() {
    let account: SymbolicVerifyTransfer = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: source is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'source is writable  /* Account marked as mutable */' */ }, "Invariant violation: source is writable  /* Account marked as mutable */");
}

/// Verify: destination is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_verifytransfer_constraint_1() {
    let account: SymbolicVerifyTransfer = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: destination is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'destination is writable  /* Account marked as mutable */' */ }, "Invariant violation: destination is writable  /* Account marked as mutable */");
}

/// Verify: authority.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_verifytransfer_constraint_2() {
    let account: SymbolicVerifyTransfer = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority.is_signer == true  /* Anchor Signer type enforces signer check */");
}

