//! Kani proof harness for Solana account: WithdrawFromEscrow
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 4

/// Symbolic representation of the Solana account for verification
struct SymbolicWithdrawFromEscrow {
    escrow: u64,
    user: u64,
}

impl kani::Arbitrary for SymbolicWithdrawFromEscrow {
    fn any() -> Self {
        Self {
            escrow: kani::any(),
            user: kani::any(),
        }
    }
}

/// Verify: escrow is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawfromescrow_constraint_0() {
    let account: SymbolicWithdrawFromEscrow = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: escrow is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'escrow is writable  /* Account marked as mutable */' */ }, "Invariant violation: escrow is writable  /* Account marked as mutable */");
}

/// Verify: escrow PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawfromescrow_constraint_1() {
    let account: SymbolicWithdrawFromEscrow = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: escrow PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'escrow PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: escrow PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: user.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawfromescrow_constraint_2() {
    let account: SymbolicWithdrawFromEscrow = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ user.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: user.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: user is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawfromescrow_constraint_3() {
    let account: SymbolicWithdrawFromEscrow = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: user is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'user is writable  /* Account marked as mutable */' */ }, "Invariant violation: user is writable  /* Account marked as mutable */");
}

